// Flat UI-copy map. Placeholder for full RU/EN i18n (see frontend-requirements.md);
// keeps literal copy out of JSX so swapping in a real i18n library later is a small change.
export const strings = {
  appTitle: 'diploma-maker',
  logoutButton: 'Log out',
  chatPanelTitle: 'AI Chat',
  chatTargetLabel: 'Write into',
  chatEmpty: 'No messages yet.',
  documentPanelTitle: 'Document',
  tocSidebarTitle: 'Contents',
  tocSidebarEmpty: 'No chapters yet.',
  documentEmpty: 'No chapters yet. Start a new project to begin.',
  documentUploadTitle: 'Already have some or all of it written?',
  documentUploadSubtitle:
    'Upload your whole document (.docx, with Heading 1 styles marking each chapter) and we will create all the chapters and bring in their content for you to review.',
  documentUploadLabel: 'Upload your whole document (.docx)',
  documentUploadButton: 'Upload document',
  documentUploadButtonPending: 'Uploading...',
  documentUploadErrorMessage:
    'Failed to split the document into chapters. Please make sure it is a .docx file with each chapter title styled as Heading 1.',
  tocUploadTitle: 'Or just upload a table of contents',
  tocUploadSubtitle: 'No content yet, just chapter titles — we will create empty chapters in order.',
  tocUploadLabel: 'Upload table of contents (.docx)',
  tocUploadButton: 'Upload TOC',
  tocUploadButtonPending: 'Uploading...',
  tocUploadErrorMessage: 'That file appears to be empty. Please upload a .docx file listing your chapter titles.',
  chapterDraftUploadLabel: 'Upload your own draft for this chapter (.docx/.pdf)',
  chapterDraftUploadButton: 'Upload draft',
  chapterDraftUploadButtonPending: 'Uploading...',
  chapterDraftUploadErrorMessage: 'Failed to upload the draft. Please make sure it is a supported .docx or .pdf file.',
  newProjectButton: 'New Project',
  diffViewerTitle: 'Pending Edit',
  diffAcceptButton: 'Accept',
  diffRejectButton: 'Reject',
  diffEmpty: 'No changes.',
  diffNewDraftHintMessage: 'Review the content below, then Accept or Reject it.',
  chatInputPlaceholder: 'Describe what you want this chapter to say...',
  chatSendButton: 'Send',
  chatDraftReadyMessage: 'Draft ready — review it in the document panel.',
  chatDraftFlaggedMessage:
    'Draft ready, but flagged by the plagiarism/AI-detection pre-check — review it carefully in the document panel.',
  chatGenerationErrorMessage: 'Generation failed. Please try again.',
  chatUnmetRequiredSourcesMessage: (sources: string[]) =>
    `Could not find/ground these required sources for this draft, so they were not cited: ${sources.join('; ')}.`,
  chapterStreamingLabel: 'Draft streaming in progress',
  defaultChapterTitle: 'Chapter 1',
  chapterContentEmpty: 'No accepted content yet.',
  documentPagePrevButton: '« Prev',
  documentPageNextButton: 'Next »',
  documentPageLabel: (current: number, total: number) => `Page ${current} of ${total}`,
  onboardingTitle: 'Welcome',
  onboardingSubtitle: 'Sign in or create an account to start drafting your thesis.',
  onboardingEmailLabel: 'Email',
  onboardingPasswordLabel: 'Password',
  onboardingRegisterButton: 'Register',
  onboardingLoginButton: 'Log in',
  onboardingAuthError: 'Registration or login failed. Please check your details and try again.',
  newProjectSetupTitle: 'Set up your new project',
  newProjectSetupSubtitle:
    'Pick your university’s formatting profile, or upload a sample document to create one. You can also skip this and create the project without one.',
  newProjectSetupOrDivider: 'Or',
  newProjectSetupInstitutionSelectLabel: 'Choose an existing university profile',
  newProjectSetupInstitutionSelectPlaceholder: 'Select a university...',
  newProjectSetupInstitutionSelectError: 'Failed to load university list. Please try again.',
  newProjectSetupInstitutionUploadTitle: 'Or upload a new university sample',
  newProjectSetupInstitutionNameLabel: 'University name',
  newProjectSetupInstitutionFileLabel: 'Sample document',
  newProjectSetupInstitutionUploadButton: 'Upload',
  newProjectSetupInstitutionUploadError: 'Failed to upload university sample. Please try again.',
  newProjectSetupAutoDetectTitle: 'Or try automatic detection',
  newProjectSetupAutoDetectSubtitle:
    "We'll search the web for your university's formatting requirements. This is best-effort and may not find anything.",
  newProjectSetupAutoDetectNameLabel: 'University name to search for',
  newProjectSetupAutoDetectButton: 'Try to auto-detect',
  newProjectSetupAutoDetectButtonPending: 'Searching...',
  newProjectSetupAutoDetectNotFoundMessage:
    "We couldn't automatically find formatting requirements for this university. Try picking it from the list above or uploading a sample document instead.",
  newProjectSetupAutoDetectError:
    'Automatic detection is unavailable right now. Please try picking from the list above or uploading a sample document instead.',
  newProjectSetupCreateButton: 'Create Project',
  newProjectSetupCancelButton: 'Cancel',
  newProjectSetupCreateError: 'Failed to create project. Please try again.',
  tabWorkspaceLabel: 'Workspace',
  tabPlagiarismCheckLabel: 'Plagiarism Check',
  plagiarismCheckTitle: 'Plagiarism Check',
  plagiarismCheckModeTextLabel: 'Paste text',
  plagiarismCheckModeFileLabel: 'Upload file',
  plagiarismCheckTextareaPlaceholder: 'Paste the text you want to check for plagiarism or AI-fingerprint risk...',
  plagiarismCheckButton: 'Check',
  plagiarismCheckButtonPending: 'Checking...',
  plagiarismCheckScoreLabel: 'Plagiarism score',
  plagiarismCheckAiFingerprintScoreLabel: 'AI-fingerprint score',
  plagiarismCheckOriginalityScoreLabel: 'Originality score',
  plagiarismCheckFlaggedMessage: 'Flagged — review this text carefully.',
  plagiarismCheckNotFlaggedMessage: 'Not flagged.',
  plagiarismCheckReasonsTitle: 'Reasons',
  plagiarismCheckErrorMessage: 'Plagiarism check failed. Please try again.',
  plagiarismCheckSentenceFlagsTitle: 'Sentence-level flags',
  plagiarismUploadFileLabel: 'Choose a .pdf or .docx file to check',
  plagiarismUploadButton: 'Check File',
  plagiarismUploadErrorMessage: 'Plagiarism check failed. Please make sure the file is a supported .pdf or .docx and try again.',
  exportButton: 'Export to .docx',
  exportButtonPending: 'Exporting...',
  exportErrorMessage: 'Export failed. Please try again.',
  projectLandingTitle: 'Your Projects',
  projectLandingEmpty: 'No projects yet. Start a new one to begin.',
  projectLandingLoadErrorMessage: 'Failed to load projects. Please try again.',
  projectLandingOpenButton: 'Open',
  projectLandingActiveLabel: 'Active',
  projectLandingDeleteButton: 'Delete',
  projectLandingDeleteConfirmButton: 'Confirm delete',
  projectLandingDeleteCancelButton: 'Cancel',
  projectLandingDeleteErrorMessage: 'Failed to delete project. Please try again.',
  myProjectsButton: 'My Projects',
  chapterTreeTitle: 'Chapters',
  chapterTreeEmpty: 'No chapters yet.',
  chapterTreeExpandLabel: 'Expand',
  chapterTreeCollapseLabel: 'Collapse',
  chapterTreeAddSubchapterButton: '+ Subchapter',
  chapterTreeAddSubchapterInputLabel: 'New subchapter title',
  chapterTreeAddSubchapterConfirmButton: 'Add',
  chapterTreeAddSubchapterCancelButton: 'Cancel',
  chapterTreeAddSubchapterErrorMessage: 'Failed to add subchapter. Please try again.',
  documentBlockLockLabel: 'Lock this block (protect it from future AI edits)',
  documentBlockUnlockLabel: 'Unlock this block',
  documentBlockInsertHereLabel: 'Insert new content here',
  documentBlockInsertHereSelectedLabel: 'Selected as insertion point (click to cancel)',
  chatInsertingAtIndicator: 'Inserting new content at the selected block.',
  chatCancelInsertionPointButton: 'Cancel insertion point',
  chatChapterFullyLockedMessage:
    'This chapter is fully locked, so there is no unlocked location to insert new content. Unlock at least one block and try again.',
  diffRerouteNoticeMessage:
    'The requested insertion point was locked, so the AI inserted this content at a nearby unlocked location instead.',
  newProjectSetupRequiredSourcesTitle: 'Required sources (optional)',
  newProjectSetupRequiredSourcesSubtitle:
    'List any authors or works your thesis must cite. We will try to ground generated chapters in them.',
  newProjectSetupRequiredSourceAuthorLabel: 'Author',
  newProjectSetupRequiredSourceTitleLabel: 'Work title (optional)',
  newProjectSetupRequiredSourceAddButton: 'Add',
  newProjectSetupRequiredSourceRemoveButton: 'Remove',
  newProjectSetupRequiredSourceBulkTitle: 'Or add many at once',
  newProjectSetupRequiredSourceBulkSubtitle:
    'Paste a whole reference list (one or many entries, any format) and we will detect the individual authors/works for you.',
  newProjectSetupRequiredSourceBulkLabel: 'Bibliography text',
  newProjectSetupRequiredSourceBulkPlaceholder: 'Paste your bibliography/reference list here...',
  newProjectSetupRequiredSourceBulkButton: 'Auto-detect from pasted text',
  newProjectSetupRequiredSourceBulkButtonPending: 'Detecting...',
  newProjectSetupRequiredSourceBulkError:
    'Could not detect sources from the pasted text. Please try again or add them one at a time above.',
  newProjectSetupRequiredSourceBulkEmptyMessage: 'No authors or works were detected in that text.',
  requiredSourcesManagerTitle: 'Required sources',
  requiredSourcesManagerSubtitle:
    'Authors/works generated chapters should cite. Add more any time — not just when creating the project.',
  requiredSourcesManagerAddError: 'Failed to add that source. Please try again.',
  requiredSourcesManagerLoadError: 'Failed to load required sources. Please try again.',
  requiredSourcesManagerEmpty: 'No required sources yet.',
  historyControlsTitle: 'Undo/Redo',
  historyUndoLastButton: 'Undo last edit',
  historyRedoLastButton: 'Redo last edit',
  historyUndoPageButton: 'Undo this page',
  historyRedoPageButton: 'Redo this page',
  historyUndoAllButton: 'Undo entire document',
  historyRedoAllButton: 'Redo entire document',
  historyConflictErrorMessage:
    'This edit history changed elsewhere (or an anchor block no longer exists). Please refresh and try again.',
  historyGenericErrorMessage: 'Undo/redo failed. Please try again.',
  historyPageRevertSpansWarning: (count: number) =>
    `Reverting this page will also undo ${count} edit(s) made elsewhere since.`,
  historyPageRedoSpansWarning: (count: number) =>
    `Redoing this page will also redo ${count} edit(s) made elsewhere since.`,
  historyPageUndoConfirmButton: (count: number) => `Yes, also undo ${count} edit(s) elsewhere`,
  historyPageRedoConfirmButton: (count: number) => `Yes, also redo ${count} edit(s) elsewhere`,
  historyPageRevertCancelButton: 'Cancel',
} as const
