// Flat UI-copy map. Placeholder for full RU/EN i18n (see frontend-requirements.md);
// keeps literal copy out of JSX so swapping in a real i18n library later is a small change.
export const strings = {
  appTitle: 'diploma-maker',
  chatPanelTitle: 'AI Chat',
  chatEmpty: 'No messages yet.',
  documentPanelTitle: 'Document',
  documentEmpty: 'No chapters yet. Start a new project to begin.',
  newProjectButton: 'New Project',
  diffViewerTitle: 'Pending Edit',
  diffAcceptButton: 'Accept',
  diffRejectButton: 'Reject',
  diffEmpty: 'No changes.',
  chatInputPlaceholder: 'Describe what you want this chapter to say...',
  chatSendButton: 'Send',
  chatDraftReadyMessage: 'Draft ready — review it in the document panel.',
  chatDraftFlaggedMessage:
    'Draft ready, but flagged by the plagiarism/AI-detection pre-check — review it carefully in the document panel.',
  chatGenerationErrorMessage: 'Generation failed. Please try again.',
  chapterStreamingLabel: 'Draft streaming in progress',
  defaultChapterTitle: 'Chapter 1',
  chapterContentEmpty: 'No accepted content yet.',
  onboardingTitle: 'Welcome',
  onboardingSubtitle: 'Sign in or create an account to start drafting your thesis.',
  onboardingEmailLabel: 'Email',
  onboardingPasswordLabel: 'Password',
  onboardingRegisterButton: 'Register',
  onboardingLoginButton: 'Log in',
  onboardingAuthError: 'Registration or login failed. Please check your details and try again.',
  onboardingInstitutionStepTitle: 'Select your university',
  onboardingInstitutionStepSubtitle:
    'Pick your university’s formatting profile, or upload a sample document to create one.',
  onboardingOrDivider: 'Or',
  onboardingInstitutionSelectLabel: 'Choose an existing university profile',
  onboardingInstitutionSelectPlaceholder: 'Select a university...',
  onboardingInstitutionSelectError: 'Failed to load university list. Please try again.',
  onboardingInstitutionUploadTitle: 'Or upload a new university sample',
  onboardingInstitutionNameLabel: 'University name',
  onboardingInstitutionFileLabel: 'Sample document',
  onboardingInstitutionUploadButton: 'Upload',
  onboardingInstitutionUploadError: 'Failed to upload university sample. Please try again.',
  onboardingInstitutionAutoDetectTitle: 'Or try automatic detection',
  onboardingInstitutionAutoDetectSubtitle:
    "We'll search the web for your university's formatting requirements. This is best-effort and may not find anything.",
  onboardingInstitutionAutoDetectNameLabel: 'University name to search for',
  onboardingInstitutionAutoDetectButton: 'Try to auto-detect',
  onboardingInstitutionAutoDetectButtonPending: 'Searching...',
  onboardingInstitutionAutoDetectNotFoundMessage:
    "We couldn't automatically find formatting requirements for this university. Try picking it from the list above or uploading a sample document instead.",
  onboardingInstitutionAutoDetectError:
    'Automatic detection is unavailable right now. Please try picking from the list above or uploading a sample document instead.',
  tabWorkspaceLabel: 'Workspace',
  tabPlagiarismCheckLabel: 'Plagiarism Check',
  plagiarismCheckTitle: 'Plagiarism Check',
  plagiarismCheckTextareaPlaceholder: 'Paste the text you want to check for plagiarism or AI-fingerprint risk...',
  plagiarismCheckButton: 'Check',
  plagiarismCheckButtonPending: 'Checking...',
  plagiarismCheckScoreLabel: 'Plagiarism score',
  plagiarismCheckAiFingerprintScoreLabel: 'AI-fingerprint score',
  plagiarismCheckFlaggedMessage: 'Flagged — review this text carefully.',
  plagiarismCheckNotFlaggedMessage: 'Not flagged.',
  plagiarismCheckReasonsTitle: 'Reasons',
  plagiarismCheckErrorMessage: 'Plagiarism check failed. Please try again.',
} as const
